### ISSUE TITLE
Usul storage.js

### ISSUE THREAD

**Issue by ombapit** [hscstudio/react-smart-app#1]
untuk storage.js, data yg dikirim lebih baik dienkrip menggunakan crypto-js.
Misal:
install: npm install crypto-js
```javascript
//panggil
var CryptoJS = require("crypto-js");

//untuk read
if (process.env.NODE_ENV === 'production') {
      newState = JSON.parse(CryptoJS.AES.decrypt(storage.get(storageKey), 'salt').toString(CryptoJS.enc.Utf8))
} else {
      newState = JSON.parse(storage.getItem(storageKey))
}

//untuk write
if (process.env.NODE_ENV === 'production') {
  data = CryptoJS.AES.encrypt(JSON.stringify(state),'salt').toString()
} else {
  data = JSON.stringify(state)
}
```
soalnya,saya coba di next.js, return value dari LZString gakbisa didapet. tp kl misal di cra aman ya gk apa2.

**Comment by hscstudio** [comment]
Iya om, tujuan lzstring buat kompress dan disimpan di localstorage nah kalo ssr atau next jelas ga bisa pake localstorge karena localstorage adanya di browser bukan dj node
